services:
  - type: web
    name: pecha-stt
    env: node
    plan: free
    # Update the following line with your Strapi GitHub repo
    repo: https://github.com/tentamdin/stt-mvp
    branch: main
    buildCommand: npm run build
    startCommand: npx prisma migrate deploy && npm run start
    envVars:
      - key: NODE_VERSION
        value: ~16.14.2
      - key: NODE_ENV
        value: production
      - key: DATABASE_URL
        fromDatabase:
          name: pecha-stt-pg
          property: connectionString

databases:
  - name: pecha-stt-pg
    plan: free
