import { Toaster } from "react-hot-toast";
import "./globals.css";

export const metadata = {
  title: "Pecha Stt Tool",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body>
        {children}
        <Toaster position="top-right" reverseOrder={false} />
      </body>
    </html>
  );
}
